


#本地环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false

server:
  port: 8081

liquibase:
  enabled: true
  change-log: classpath:db-changelog.xml
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/test